// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ProtocolDummyFactory.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test (1.55.27)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Protocol.Domain.Test
{
    using System;

    using FakeItEasy;

    using OBeautifulCode.AutoFakeItEasy;

    /// <summary>
    /// A Dummy Factory for types in <see cref="Naos.Protocol.Domain"/>.
    /// </summary>
#if !NaosProtocolRecipesProject
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Protocol.Domain.Test", "See package version number")]
#endif
    public class ProtocolDummyFactory : DefaultProtocolDummyFactory
    {
        public ProtocolDummyFactory()
        {
            /* Add any overriding or custom registrations here. */
        }
    }
}
