// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.137.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Protocol.Domain.Test
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;

    using global::FakeItEasy;

    using global::Naos.Protocol.Domain;

    using global::OBeautifulCode.AutoFakeItEasy;
    using global::OBeautifulCode.Math.Recipes;
    using global::OBeautifulCode.Representation.System;
    using global::OBeautifulCode.Type;

    /// <summary>
    /// The default (code generated) Dummy Factory.
    /// Derive from this class to add any overriding or custom registrations.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [GeneratedCode("OBeautifulCode.CodeGen.ModelObject", "1.0.137.0")]
#if !NaosProtocolSolution
    internal
#else
    public
#endif
    abstract class DefaultProtocolDummyFactory : IDummyFactory
    {
        public DefaultProtocolDummyFactory()
        {
            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ExecuteDefaultOperationsOnProtocolOp(
                                 A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>(
                                 A.Dummy<Version>(),
                                 A.Dummy<DateTime>(),
                                 A.Dummy<GetProtocolByTypeOp>(),
                                 A.Dummy<IReadOnlyDictionary<string, string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new FailedToHandleEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>(
                                 A.Dummy<Version>(),
                                 A.Dummy<string>(),
                                 A.Dummy<DateTime>(),
                                 A.Dummy<IReadOnlyDictionary<string, string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new HandleEventOp<ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>(
                                 A.Dummy<ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new RecordedObjectEvent<Version, Version>(
                                 A.Dummy<Version>(),
                                 A.Dummy<DateTime>(),
                                 A.Dummy<Version>(),
                                 A.Dummy<IReadOnlyDictionary<string, string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetIdFromObjectOp<Version, Version>(
                                 A.Dummy<Version>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetTagsFromObjectOp<Version>(
                                 A.Dummy<Version>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetProtocolByTypeOp(
                                 A.Dummy<TypeRepresentation>(),
                                 A.Dummy<MissingProtocolStrategy>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetReturningProtocolOp<GetIdFromObjectOp<Version, Version>, Version>());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetVoidProtocolOp<ExecuteDefaultOperationsOnProtocolOp>());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new CacheResult<Version, Version>(
                                 A.Dummy<Version>(),
                                 A.Dummy<Version>(),
                                 A.Dummy<DateTime>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new CacheStatusResult(
                                 A.Dummy<long>(),
                                 A.Dummy<UtcDateTimeRangeInclusive>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ClearCacheOp());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetCacheStatusOp());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetOrAddCachedItemOp<GetIdFromObjectOp<Version, Version>, Version>(
                                 A.Dummy<GetIdFromObjectOp<Version, Version>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetAllResourceLocatorsOp());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetResourceLocatorByIdOp<Version>(
                                 A.Dummy<Version>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetResourceLocatorForUniqueIdentifierOp());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new NullResourceLocator());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ThrowIfResourceUnavailableOp(
                                 A.Dummy<ResourceLocatorBase>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>),
                        typeof(FailedToHandleEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>),
                        typeof(RecordedObjectEvent<Version, Version>),
                        typeof(HandledEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>),
                        typeof(HandlingEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (EventBaseBase)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>),
                        typeof(FailedToHandleEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>),
                        typeof(RecordedObjectEvent<Version, Version>),
                        typeof(HandledEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>),
                        typeof(HandlingEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (EventBase<Version>)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ExecuteDefaultOperationsOnProtocolOp),
                        typeof(HandleEventOp<ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>),
                        typeof(GetIdFromObjectOp<Version, Version>),
                        typeof(GetTagsFromObjectOp<Version>),
                        typeof(GetProtocolByTypeOp),
                        typeof(GetReturningProtocolOp<GetIdFromObjectOp<Version, Version>, Version>),
                        typeof(GetVoidProtocolOp<ExecuteDefaultOperationsOnProtocolOp>),
                        typeof(ClearCacheOp),
                        typeof(GetCacheStatusOp),
                        typeof(GetOrAddCachedItemOp<GetIdFromObjectOp<Version, Version>, Version>),
                        typeof(GetAllResourceLocatorsOp),
                        typeof(GetResourceLocatorByIdOp<Version>),
                        typeof(GetResourceLocatorForUniqueIdentifierOp),
                        typeof(ThrowIfResourceUnavailableOp)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (OperationBase)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(GetIdFromObjectOp<Version, Version>)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (ReturningOperationBase<Version>)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ExecuteDefaultOperationsOnProtocolOp),
                        typeof(HandleEventOp<ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>),
                        typeof(ClearCacheOp),
                        typeof(ThrowIfResourceUnavailableOp)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (VoidOperationBase)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new HandledEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>(
                                 A.Dummy<Version>(),
                                 A.Dummy<DateTime>(),
                                 A.Dummy<string>(),
                                 A.Dummy<IReadOnlyDictionary<string, string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new HandlingEventEvent<Version, ExecuteOperationRequestedEvent<Version, GetProtocolByTypeOp>>(
                                 A.Dummy<Version>(),
                                 A.Dummy<DateTime>(),
                                 A.Dummy<string>(),
                                 A.Dummy<IReadOnlyDictionary<string, string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new NamedResourceLocator(
                                 A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(NullResourceLocator),
                        typeof(NamedResourceLocator)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (ResourceLocatorBase)AD.ummy(randomType);

                    return result;
                });
        }

        /// <inheritdoc />
        public Priority Priority => new FakeItEasy.Priority(1);

        /// <inheritdoc />
        public bool CanCreate(Type type)
        {
            return false;
        }

        /// <inheritdoc />
        public object Create(Type type)
        {
            return null;
        }
    }
}