// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SerializationConfigurationTypes.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test (1.55.27)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Protocol.Domain.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Diagnostics.CodeAnalysis;

    using Naos.Protocol.Serialization.Bson;
    using Naos.Protocol.Serialization.Json;

    [ExcludeFromCodeCoverage]
    [GeneratedCode("Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test", "1.55.27")]
    public static class SerializationConfigurationTypes
    {
        public static Type BsonSerializationConfigurationType => typeof(ProtocolBsonSerializationConfiguration);

        public static Type JsonSerializationConfigurationType => typeof(ProtocolJsonSerializationConfiguration);
    }
}
