// --------------------------------------------------------------------------------------------------------------------
// <copyright file="EqualityCodeGenerationHelper.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.Bootstrapper source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

using System;

namespace Naos.Bootstrapper.Test
{
    /// <summary>
    /// Helper methods for creating object equality and hash code text via reflection.
    /// </summary>
    #if !NaosBootstrapperTest
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [System.CodeDom.Compiler.GeneratedCode("Naos.Bootstrapper.Test", "See package version number")]
    #endif
    public class EqualityCodeGenerationHelper
    {
        /// <summary>
        /// Creates the necessary code to implement <see cref="IEquatable{T}" /> for the supplied type.
        /// </summary>
        /// <param name="objectType"></param>
        /// <returns></returns>
        public string GenerateEqualityLogic(Type objectType)
        {
            throw new NotImplementedException();
        }
    }
}